In [17]:
import pandas as pd
import os

group_name = "gangnam_1"

predictor_file_name = "../input/participant_demo_clinical_all.csv"

variable_of_interest_list = ['LSAS', 'LSAS_performance', 'LSAS_social_interaction', 'BFNE']

columns_of_interest = ['1. SEX', '2.AGE', '3-2. YR_EDU', 'fmri_code', 'LSAS', 
                       'LSAS_performance', 'LSAS_social_interaction', 'BFNE']


predictor = pd.read_csv(predictor_file_name)
predictor

,Unnamed: 0,HAID ID,GROUP,Exp No.,1. SEX,2.AGE,3-2. YR_EDU,fmri_code,Screening #,Enrollment #,...,LSAS,MOCI,MOCI_checking,MOCI_cleaning,MOCI_doubting,MOCI_slowness,BFNE,PSWQ,Handedness(true),FCV-19S
0,0,0827jck,EXP,7,2,20,12.0,s0007,1.0,EXP-0001,...,98.0,19.0,4.0,8.0,5.0,4.0,56.0,58.0,48.0,7.0
1,1,na0840,EXP,5,2,20,12.0,s0005,2.0,EXP-0002,...,80.0,15.0,5.0,6.0,3.0,2.0,57.0,62.0,40.0,18.0
2,2,spwls915,EXP,4,2,21,15.0,s0004,3.0,EXP-0003,...,95.0,18.0,6.0,10.0,1.0,5.0,59.0,60.0,40.0,5.0
3,3,wkddbswns,HC,9,1,25,15.0,c0009,4.0,HC-0001,...,18.0,24.0,7.0,11.0,3.0,7.0,35.0,47.0,47.0,2.0
4,4,bje5409,EXP,12,2,30,12.0,s0012,5.0,EXP-0004,...,57.0,26.0,8.0,11.0,4.0,7.0,51.0,50.0,47.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,159,kimhg2004,EXP,574,2,19,12.0,s0574,160.0,EXP-0086,...,65.0,8.0,4.0,0.0,3.0,2.0,47.0,38.0,36.0,5.0
160,160,miss20c,EXP,562,2,39,20.0,s0562,161.0,EXP-0087,...,35.0,13.0,5.0,2.0,6.0,1.0,44.0,51.0,44.0,4.0
161,161,goun4238,EXP,583,1,19,12.0,s0583,162.0,EXP-0088,...,105.0,20.0,8.0,2.0,6.0,6.0,53.0,67.0,48.0,6.0
162,162,yyyyjg,HC,549,2,35,NaN,c0549,167.0,HC-0076,...,24.0,4.0,1.0,0.0,2.0,1.0,41.0,45.0,46.0,0.0
163,163,bbclar,EXP,618,1,29,16.0,s0618,163.0,EXP-0089,...,86.0,15.0,6.0,1.0,6.0,4.0,50.0,71.0,39.0,2.0

In [18]:
cleaned_predictor = predictor.dropna(subset=columns_of_interest)
cleaned_predictor

,Unnamed: 0,HAID ID,GROUP,Exp No.,1. SEX,2.AGE,3-2. YR_EDU,fmri_code,Screening #,Enrollment #,...,LSAS,MOCI,MOCI_checking,MOCI_cleaning,MOCI_doubting,MOCI_slowness,BFNE,PSWQ,Handedness(true),FCV-19S
0,0,0827jck,EXP,7,2,20,12.0,s0007,1.0,EXP-0001,...,98.0,19.0,4.0,8.0,5.0,4.0,56.0,58.0,48.0,7.0
1,1,na0840,EXP,5,2,20,12.0,s0005,2.0,EXP-0002,...,80.0,15.0,5.0,6.0,3.0,2.0,57.0,62.0,40.0,18.0
2,2,spwls915,EXP,4,2,21,15.0,s0004,3.0,EXP-0003,...,95.0,18.0,6.0,10.0,1.0,5.0,59.0,60.0,40.0,5.0
3,3,wkddbswns,HC,9,1,25,15.0,c0009,4.0,HC-0001,...,18.0,24.0,7.0,11.0,3.0,7.0,35.0,47.0,47.0,2.0
4,4,bje5409,EXP,12,2,30,12.0,s0012,5.0,EXP-0004,...,57.0,26.0,8.0,11.0,4.0,7.0,51.0,50.0,47.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,158,nuge22,EXP,556,1,29,16.0,s0556,159.0,EXP-0085,...,67.0,12.0,4.0,1.0,5.0,2.0,56.0,55.0,48.0,2.0
159,159,kimhg2004,EXP,574,2,19,12.0,s0574,160.0,EXP-0086,...,65.0,8.0,4.0,0.0,3.0,2.0,47.0,38.0,36.0,5.0
160,160,miss20c,EXP,562,2,39,20.0,s0562,161.0,EXP-0087,...,35.0,13.0,5.0,2.0,6.0,1.0,44.0,51.0,44.0,4.0
161,161,goun4238,EXP,583,1,19,12.0,s0583,162.0,EXP-0088,...,105.0,20.0,8.0,2.0,6.0,6.0,53.0,67.0,48.0,6.0
163,163,bbclar,EXP,618,1,29,16.0,s0618,163.0,EXP-0089,...,86.0,15.0,6.0,1.0,6.0,4.0,50.0,71.0,39.0,2.0

In [19]:
import os
import re
fmriprep_dir = "/mnt/NAS2/data/SAD_gangnam_resting/fMRIPrep/"
# List all files and directories in the given path
items = os.listdir(fmriprep_dir)

# Define a regex pattern to match the codes
pattern = re.compile(r'sub-(c\d{4}|s\d{4})')

# Extract unique codes
unique_codes = set()
for item in items:
    match = pattern.match(item)
    if match:
        unique_codes.add(match.group(1))

# Convert the set to a sorted list
unique_codes = sorted(list(unique_codes))

In [20]:
# Filter the cleaned_predictor dataframe to include only rows with fmri_code matching unique_codes
filtered_predictor = cleaned_predictor[cleaned_predictor['fmri_code'].isin(unique_codes)]
filtered_predictor

,Unnamed: 0,HAID ID,GROUP,Exp No.,1. SEX,2.AGE,3-2. YR_EDU,fmri_code,Screening #,Enrollment #,...,LSAS,MOCI,MOCI_checking,MOCI_cleaning,MOCI_doubting,MOCI_slowness,BFNE,PSWQ,Handedness(true),FCV-19S
0,0,0827jck,EXP,7,2,20,12.0,s0007,1.0,EXP-0001,...,98.0,19.0,4.0,8.0,5.0,4.0,56.0,58.0,48.0,7.0
1,1,na0840,EXP,5,2,20,12.0,s0005,2.0,EXP-0002,...,80.0,15.0,5.0,6.0,3.0,2.0,57.0,62.0,40.0,18.0
2,2,spwls915,EXP,4,2,21,15.0,s0004,3.0,EXP-0003,...,95.0,18.0,6.0,10.0,1.0,5.0,59.0,60.0,40.0,5.0
3,3,wkddbswns,HC,9,1,25,15.0,c0009,4.0,HC-0001,...,18.0,24.0,7.0,11.0,3.0,7.0,35.0,47.0,47.0,2.0
4,4,bje5409,EXP,12,2,30,12.0,s0012,5.0,EXP-0004,...,57.0,26.0,8.0,11.0,4.0,7.0,51.0,50.0,47.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,146,dlcnddus,HC,519,2,45,16.0,c0519,147.0,HC-0070,...,49.0,7.0,1.0,2.0,3.0,1.0,29.0,44.0,47.0,0.0
150,150,hong94,HC,552,1,29,15.0,c0552,151.0,HC-0071,...,13.0,2.0,2.0,0.0,0.0,0.0,29.0,33.0,43.0,0.0
151,151,sunset,HC,546,1,29,16.0,c0546,152.0,HC-0072,...,19.0,8.0,2.0,1.0,4.0,1.0,40.0,30.0,40.0,2.0
153,153,bpark0718,HC,547,2,28,12.0,c0547,154.0,HC-0073,...,45.0,8.0,3.0,0.0,3.0,2.0,43.0,25.0,42.0,2.0
155,155,robin4760,HC,518,2,25,12.0,c0518,156.0,HC-0074,...,8.0,5.0,1.0,0.0,4.0,0.0,38.0,37.0,41.0,4.0

In [21]:
participant_df = filtered_predictor.rename(columns={
    'fmri_code': 'Participant',
    '1. SEX': 'SEX',
    '2.AGE': 'AGE',
    '3-2. YR_EDU': 'YR_EDU'
})[['Participant', 'SEX', 'AGE', 'YR_EDU', 'LSAS', 'LSAS_performance', 'LSAS_social_interaction', 'BFNE']]
participant_df['SEX'] = participant_df['SEX'].map({1: 1, 2: 0})
participant_df

,Participant,SEX,AGE,YR_EDU,LSAS,LSAS_performance,LSAS_social_interaction,BFNE
0,s0007,0,20,12.0,98.0,51.0,47.0,56.0
1,s0005,0,20,12.0,80.0,50.0,30.0,57.0
2,s0004,0,21,15.0,95.0,51.0,44.0,59.0
3,c0009,1,25,15.0,18.0,9.0,9.0,35.0
4,s0012,0,30,12.0,57.0,37.0,20.0,51.0
...,...,...,...,...,...,...,...,...
146,c0519,0,45,16.0,49.0,26.0,23.0,29.0
150,c0552,1,29,15.0,13.0,7.0,6.0,29.0
151,c0546,1,29,16.0,19.0,9.0,10.0,40.0
153,c0547,0,28,12.0,45.0,22.0,23.0,43.0
155,c0518,0,25,12.0,8.0,6.0,2.0,38.0

In [22]:
def save_variable_of_interest(df, variables):
    for variable in variables:
        # Select the necessary columns
        df_subset = df[['Participant', 'SEX', 'AGE', 'YR_EDU', variable]]
        
        # Create the filename
        base_dir = "/home/changbae/fmri_project/C-PAC/CPAC/bcb_mdmr/input/"
        filename = f"{base_dir}gangnam_1_{variable}_regressor.csv"
        
        # Save the DataFrame to a CSV file
        df_subset.to_csv(filename, index=False)
        print(f"Saved {filename}")

In [23]:
save_variable_of_interest(participant_df,variable_of_interest_list)

Saved /home/changbae/fmri_project/C-PAC/CPAC/bcb_mdmr/input/gangnam_1_LSAS_regressor.csv
Saved /home/changbae/fmri_project/C-PAC/CPAC/bcb_mdmr/input/gangnam_1_LSAS_performance_regressor.csv
Saved /home/changbae/fmri_project/C-PAC/CPAC/bcb_mdmr/input/gangnam_1_LSAS_social_interaction_regressor.csv
Saved /home/changbae/fmri_project/C-PAC/CPAC/bcb_mdmr/input/gangnam_1_BFNE_regressor.csv

In [25]:
# Save the 'Participant' column to a separate CSV file
participant_codes = participant_df[['Participant']]

# Save the DataFrame to a CSV file
participant_codes.to_csv("/home/changbae/fmri_project/C-PAC/CPAC/bcb_mdmr/input/gangnam_1_code_list.csv", index=False, header=False)
print("Saved participant codes")

Saved participant codes